steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west1-docker.pkg.dev/$PROJECT_ID/docker/un2720-scraper', '-f', 'scripts/Dockerfile.scrape', 'scripts']
images:
  - 'europe-west1-docker.pkg.dev/$PROJECT_ID/docker/un2720-scraper'
